version: '3'
services:
    app:
        container_name: library-rest-api
        restart: always
        build: .
        ports:
            - '80:3000'
        external_links:
            - mongo
        environment:
            - DB_URL=mongodb://mongo:27017/library
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
