name: Node.js CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 16.x]

        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Create mongoDB Docker container for API testing
              uses: DigiPie/mongo-action@v1.0.1
            - name: Install npm packages
              run: npm ci
            - name: Run npm dev server
              run: node server.js
              env:
                  CI: true
                  DB_URL: mongodb://localhost:27017/library
                  NODE_ENV: production
                  PORT: 3000
                  JWT_SECRET: samplecitestsecrethahajkjkunless??
                  JWT_EXPIRE_TIME: 1h
                  SALT_ROUNDS: 10
            - name: Run `npm test:actions`
              run: npm run test:actions
